services:
  # Backend Service
  - type: web
    name: your-app-backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    plan: free  # or starter/standard
    buildCommand: ""  # Docker handles the build
    startCommand: ""  # Docker handles the start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: your-postgres-db
          property: connectionString
      - key: PORT
        value: 10000  # Render's default port
    healthCheckPath: /health  # Optional: add health check endpoint

  # Frontend Service  
  - type: web
    name: your-app-frontend
    env: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    plan: free
    buildCommand: ""
    startCommand: ""
    envVars:
      - key: VITE_API_URL  # or REACT_APP_API_URL if React
        value: https://your-app-backend.onrender.com
      - key: NODE_ENV
        value: production

# Database
databases:
  - name: your-postgres-db
    databaseName: your_database_name
    user: your_username
    plan: free  # 90 days free, then $7/month
